# Boucles, Indices, Valeurs : exercices complémentaires

## ex 1

Créer une liste l1 qui contient les cubes des entiers pairs de 2 à 50 compris (avec une boucle `for` et `range`, par exemple).

In [3]:
# réponse [8,64,216,...,125000]
l1 = []
for v in range(2,51):
    if v%2==0:
        l1.append(v**3)
print(l1)

# version compréhension
l1 = [v**3 for v in range(2,51) if v%2==0]
print(l1)

[8, 64, 216, 512, 1000, 1728, 2744, 4096, 5832, 8000, 10648, 13824, 17576, 21952, 27000, 32768, 39304, 46656, 54872, 64000, 74088, 85184, 97336, 110592, 125000]
[8, 64, 216, 512, 1000, 1728, 2744, 4096, 5832, 8000, 10648, 13824, 17576, 21952, 27000, 32768, 39304, 46656, 54872, 64000, 74088, 85184, 97336, 110592, 125000]


Augmentez chaque valeur de la liste de 1.

In [4]:
#réponse  [9, 65, 217, ..., 125001]
for i in range(len(l1)):
    l1[i] += 1
print(l1)

[9, 65, 217, 513, 1001, 1729, 2745, 4097, 5833, 8001, 10649, 13825, 17577, 21953, 27001, 32769, 39305, 46657, 54873, 64001, 74089, 85185, 97337, 110593, 125001]


Maintenant, remplacez les multiples de 3, dans cette liste, par des 0.

In [5]:
# réponse [0, 65, 217, 0, 1001, ..., 110593, 0]
for i in range(len(l1)):
    if l1[i]%3==0:
        l1[i]=0
print(l1)

[0, 65, 217, 0, 1001, 1729, 0, 4097, 5833, 0, 10649, 13825, 0, 21953, 27001, 0, 39305, 46657, 0, 64001, 74089, 0, 97337, 110593, 0]


## ex 2

Créez une nouvelle liste `l2`qui contient les entiers 0,1,2,..,9,0,1,...,9, ...,0,1,...9 (10 fois de suites, longueur 100 en tout).

In [17]:
l2 = []
for i in range(10):
    l2.extend(list(range(10)))
print(l2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Augmentez chaque entrée de l2 du nombre de fois qu'elle est déjà apparue avant (ainsi, le premier 2 va rester 2, le deuxième 2 va passer à 3, ..., le dernier 2 va passer à 2+9=11). Faites au plus efficace.

In [18]:
apparitions = [0 for i in range(10)] # 0 apparitions pour tous les chiffres

for i in range(len(l2)):
    mem = l2[i]
    l2[i] += apparitions[l2[i]]
    apparitions[mem] += 1

print(l2)
# réponse [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, ..., 17, 18]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


Maintenant, additionnez à chaque entrée sa valeur précédente (sauf le premier 0 qui reste 0).

In [19]:
for i in range(1,len(l2)):
    l2[i] += l2[i-1]
print(l2)
# reponse [0, 1, 3, 6, 10, ..., 865, 882, 900]

[0, 1, 3, 6, 10, 15, 21, 28, 36, 45, 46, 48, 51, 55, 60, 66, 73, 81, 90, 100, 102, 105, 109, 114, 120, 127, 135, 144, 154, 165, 168, 172, 177, 183, 190, 198, 207, 217, 228, 240, 244, 249, 255, 262, 270, 279, 289, 300, 312, 325, 330, 336, 343, 351, 360, 370, 381, 393, 406, 420, 426, 433, 441, 450, 460, 471, 483, 496, 510, 525, 532, 540, 549, 559, 570, 582, 595, 609, 624, 640, 648, 657, 667, 678, 690, 703, 717, 732, 748, 765, 774, 784, 795, 807, 820, 834, 849, 865, 882, 900]


## ex 3

Construisez une liste l3 qui ne contient que les valeurs paires de l2.

In [22]:
l3 = []
for v in l2:
    if v%2==0:
        l3.append(v)
print(l3)

#version compréhension
l3 = [v for v in l2 if v%2==0]
print(l3)
# reponse [0, 6, 10, 28, 36, 46,...,900]

[0, 6, 10, 28, 36, 46, 48, 60, 66, 90, 100, 102, 114, 120, 144, 154, 168, 172, 190, 198, 228, 240, 244, 262, 270, 300, 312, 330, 336, 360, 370, 406, 420, 426, 450, 460, 496, 510, 532, 540, 570, 582, 624, 640, 648, 678, 690, 732, 748, 774, 784, 820, 834, 882, 900]
[0, 6, 10, 28, 36, 46, 48, 60, 66, 90, 100, 102, 114, 120, 144, 154, 168, 172, 190, 198, 228, 240, 244, 262, 270, 300, 312, 330, 336, 360, 370, 406, 420, 426, 450, 460, 496, 510, 532, 540, 570, 582, 624, 640, 648, 678, 690, 732, 748, 774, 784, 820, 834, 882, 900]


Construisez une liste l4 qui contient les valeurs de l3 jusqu'au premier multiple non nul de 27, inclus.

In [23]:
l4 = []
for v in l3:
    l4.append(v)
    if v!=0 and v%27==0:
        break
print(l4)
# reponse [0, 6, 10, 28, ..., 262, 270]

[0, 6, 10, 28, 36, 46, 48, 60, 66, 90, 100, 102, 114, 120, 144, 154, 168, 172, 190, 198, 228, 240, 244, 262, 270]


## ex 4

In [28]:
#en principe on a
l4 = [0, 6, 10, 28, 36, 46, 48, 60, 66, 90, 100, 102, 114, 120, 
      144, 154, 168, 172, 190, 198, 228, 240, 244, 262, 270]

Reprendre la liste l4 et décalez ses éléments circulairement en avant : le 6 écrase le 0, le 10 écrase le 6, etc, jusqu'au 270 qui écrase 262 et finalement remplacez 270 par 0.

In [29]:
mem = l4[0]
for i in range(len(l4)-1):
    l4[i] = l4[i+1]
l4[len(l4)-1] = mem
print(l4)
# reponse [6, 10, 28, 36, ..., 270, 0]

[6, 10, 28, 36, 46, 48, 60, 66, 90, 100, 102, 114, 120, 144, 154, 168, 172, 190, 198, 228, 240, 244, 262, 270, 0]


Reprenez cette nouvelle liste et décalez la maintenant circulairement dans l'autre sens. On devrait retrouver la version précédente de l4.

In [30]:
mem = l4[len(l4)-1]
for i in range(len(l4)-1,0,-1):
    l4[i] = l4[i-1]
l4[0] = mem
print(l4)
# reponse [6, 10, 28, 36, ..., 270, 0]

[0, 6, 10, 28, 36, 46, 48, 60, 66, 90, 100, 102, 114, 120, 144, 154, 168, 172, 190, 198, 228, 240, 244, 262, 270]


# ex 5

La suite de Fibonacci est définie par :
    - les deux premiers termes sont 1 et 1
    - chaque terme est ensuite la somme des deux précédents

Créer une liste qui contient les 30 premiers termes de la suite de Fibonacci.

In [32]:
fibo = [1,1]
for i in range(2,30):
    fibo.append(fibo[i-1]+fibo[i-2])
print(fibo)

#version classe
fibo = [1,1]
for i in range(28):
    fibo.append(fibo[-1]+fibo[-2])
print(fibo)
#reponse f = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040]

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040]


Voici deux propriétés de la suite de Fibonacci. Essayez de les comprendre et de les vérifier sur les 30 termes calculés.

**propriété 1**

Le carré d'un terme est le produit des termes qui l'entourent, plus ou moins 1.  
Par exemple ̀5\*\*2 = 25 et 3\*8 = 24  
Par exemple 55\*\*2 = 3025 et 34\*89 = 3026

**propriété 2**  
Le quotient d'un terme par le précédent se rapproche du nombre d'or, qui est solution de l'équation x\**2 = x +1 .

In [33]:
p1 = True
for i in range(1,len(fibo)-2):
    if fibo[i]**2!=fibo[i-1]*fibo[i+1]+1 and fibo[i]**2!=fibo[i-1]*fibo[i+1]-1:
        p1 = False
        break
print("propriété1:",p1)

proposition1: True


In [42]:
for i in range(1,len(fibo)):
    print(fibo[i]/fibo[i-1])

from math import sqrt
delta = (-1)**2-4*1*-1 #discriminant b²-4*a*c
sol2 = (-(-1)+sqrt(delta))/(2*1) # solution 2: (-b+racine(delta))/(2*a)
print("sol2=",sol2)

1.0
2.0
1.5
1.6666666666666667
1.6
1.625
1.6153846153846154
1.619047619047619
1.6176470588235294
1.6181818181818182
1.6179775280898876
1.6180555555555556
1.6180257510729614
1.6180371352785146
1.618032786885246
1.618034447821682
1.6180338134001253
1.618034055727554
1.6180339631667064
1.6180339985218033
1.618033985017358
1.6180339901755971
1.618033988205325
1.618033988957902
1.6180339886704431
1.6180339887802426
1.618033988738303
1.6180339887543225
1.6180339887482036
sol2= 1.618033988749895
